using System.Security.Cryptography;
using System.Text;
using Ntilde.Platform.Ssh.Models;

namespace Ntilde.Platform.Ssh.OpenSsh;

public sealed class OpenSshConfigCompiler : IOpenSshConfigCompiler
{
    private readonly object _syncRoot = new();
    private readonly string _sshRootDirectory;
    private readonly string _generatedConfigPath;
    private readonly string _generatedHashPath;
    private readonly OpenSshCompilerOptions _options;

    public OpenSshConfigCompiler(string? sshRootDirectory = null, OpenSshCompilerOptions? options = null)
    {
        _sshRootDirectory = string.IsNullOrWhiteSpace(sshRootDirectory)
            ? GetDefaultSshRootDirectory()
            : Path.GetFullPath(sshRootDirectory);
        _generatedConfigPath = Path.Combine(_sshRootDirectory, "ssh_config.generated");
        _generatedHashPath = Path.Combine(_sshRootDirectory, "ssh_config.generated.hash");
        _options = options ?? new OpenSshCompilerOptions();
    }

    public OpenSshCompilationResult Compile(IReadOnlyList<SshProfile> profiles, Guid launchProfileId)
    {
        ArgumentNullException.ThrowIfNull(profiles);

        SshProfile launchProfile = profiles.FirstOrDefault(p => p.Id == launchProfileId)
            ?? throw new InvalidOperationException($"SSH profile '{launchProfileId}' was not found.");

        List<SshProfile> orderedProfiles = profiles
            .OrderBy(profile => profile.Id)
            .Select(CloneProfile)
            .ToList();

        string configText = BuildConfigText(orderedProfiles);
        string newHash = ComputeHash(configText);

        lock (_syncRoot)
        {
            Directory.CreateDirectory(_sshRootDirectory);
            Directory.CreateDirectory(Path.Combine(_sshRootDirectory, "mux"));
            if (_options.IsolateKnownHosts)
            {
                Directory.CreateDirectory(Path.GetDirectoryName(GetKnownHostsFilePath())!);
            }

            bool isCached = false;
            if (File.Exists(_generatedConfigPath) && File.Exists(_generatedHashPath))
            {
                try
                {
                    string existingHash = File.ReadAllText(_generatedHashPath).Trim();
                    isCached = string.Equals(existingHash, newHash, StringComparison.Ordinal);
                }
                catch
                {
                    isCached = false;
                }
            }

            if (!isCached)
            {
                WriteFileAtomically(_generatedConfigPath, configText);
                WriteFileAtomically(_generatedHashPath, newHash);
            }
        }

        return new OpenSshCompilationResult
        {
            ConfigFilePath = _generatedConfigPath,
            Alias = BuildAlias(launchProfile.Id)
        };
    }

    private string ComputeHash(string text)
    {
        byte[] bytes = Encoding.UTF8.GetBytes(text);
        byte[] hashBytes = SHA256.HashData(bytes);
        return Convert.ToHexString(hashBytes);
    }

    private string BuildConfigText(IReadOnlyList<SshProfile> profiles)
    {
        var sb = new StringBuilder(2048);
        sb.AppendLine("# Auto-generated by Ntilde. Changes will be overwritten.");
        sb.AppendLine();

        foreach (SshProfile profile in profiles)
        {
            AppendHostBlock(sb, profile);
        }

        return sb.ToString();
    }

    private void AppendHostBlock(StringBuilder sb, SshProfile profile)
    {
        sb.Append("Host ").Append(BuildAlias(profile.Id)).AppendLine();
        foreach (string option in BuildHostOptions(profile))
        {
            sb.Append("  ").Append(option).AppendLine();
        }

        sb.AppendLine();
    }

    /// <summary>
    /// The options of <paramref name="profile"/>'s <c>Host</c> block, one config line each, unindented and without
    /// the <c>Host</c> line: what <see cref="Compile"/> writes under the profile's alias. Each is also a valid
    /// <c>ssh -o</c> argument, since ssh reads an <c>-o</c> as a config line: what a plan that reads no config
    /// file passes instead (<see cref="Ntilde.Platform.Ssh.Launch.SshLaunchPlanner.PlanFor"/>).
    /// </summary>
    public IReadOnlyList<string> BuildHostOptions(SshProfile profile)
    {
        ArgumentNullException.ThrowIfNull(profile);
        var options = new List<string> { "HostName " + EscapeValue(profile.Host.Trim()) };

        if (!string.IsNullOrWhiteSpace(profile.User))
        {
            options.Add("User " + EscapeValue(profile.User.Trim()));
        }

        int port = profile.Port > 0 ? profile.Port : 22;
        int serverAliveInterval = profile.ServerAliveIntervalSeconds > 0 ? profile.ServerAliveIntervalSeconds : 30;
        int serverAliveCountMax = profile.ServerAliveCountMax > 0 ? profile.ServerAliveCountMax : 3;
        options.Add("Port " + port.ToString());
        options.Add("ServerAliveInterval " + serverAliveInterval.ToString());
        options.Add("ServerAliveCountMax " + serverAliveCountMax.ToString());

        if (profile.AuthMode == SshAuthMode.IdentityFile && !string.IsNullOrWhiteSpace(profile.IdentityFilePath))
        {
            options.Add("IdentityFile " + EscapeValue(profile.IdentityFilePath.Trim()));
            options.Add("IdentitiesOnly yes");
        }

        string jumpChain = BuildProxyJumpValue(profile.JumpHops);
        if (!string.IsNullOrEmpty(jumpChain))
        {
            options.Add("ProxyJump " + jumpChain);
        }

        foreach (PortForward forward in profile.Forwards)
        {
            if (ForwardOption(forward) is { } line)
            {
                options.Add(line);
            }
        }

        if (_options.IsolateKnownHosts)
        {
            options.Add("UserKnownHostsFile " + EscapeValue(GetKnownHostsFilePath()));
        }

        AddMuxOptions(options, profile);
        return options;
    }

    private void AddMuxOptions(List<string> options, SshProfile profile)
    {
        if (!profile.MuxOptions.Enabled)
        {
            return;
        }

        if (profile.MuxOptions.ControlMasterAuto)
        {
            options.Add("ControlMaster auto");
        }

        if (profile.MuxOptions.ControlPersistSeconds > 0)
        {
            options.Add("ControlPersist " + profile.MuxOptions.ControlPersistSeconds.ToString());
        }

        string controlPath = GetResolvedControlPath(profile);
        options.Add("ControlPath " + EscapeValue(controlPath));
    }

    private string GetResolvedControlPath(SshProfile profile)
    {
        string raw = profile.MuxOptions.ControlPath?.Trim() ?? string.Empty;
        if (string.IsNullOrEmpty(raw))
        {
            raw = Path.Combine(_sshRootDirectory, "mux", "cm_%id%");
        }

        string profileIdToken = profile.Id.ToString("N");
        return raw.Replace("%id%", profileIdToken, StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>The config line for <paramref name="forward"/>, or null for one that is incomplete.</summary>
    private static string? ForwardOption(PortForward forward)
    {
        if (forward.SourcePort <= 0)
        {
            return null;
        }

        string bind = string.IsNullOrWhiteSpace(forward.BindAddress)
            ? forward.SourcePort.ToString()
            : $"{forward.BindAddress.Trim()}:{forward.SourcePort}";

        switch (forward.Kind)
        {
            case PortForwardKind.Local:
            case PortForwardKind.Remote:
                if (string.IsNullOrWhiteSpace(forward.DestinationHost) || forward.DestinationPort <= 0)
                {
                    return null;
                }

                string keyword = forward.Kind == PortForwardKind.Local ? "LocalForward" : "RemoteForward";
                return $"{keyword} {bind} {forward.DestinationHost.Trim()}:{forward.DestinationPort.ToString()}";

            case PortForwardKind.Dynamic:
                return "DynamicForward " + bind;

            default:
                return null;
        }
    }

    private static string BuildProxyJumpValue(IEnumerable<SshJumpHop> jumpHops)
    {
        List<string> chain = new();

        foreach (SshJumpHop hop in jumpHops)
        {
            if (string.IsNullOrWhiteSpace(hop.Host))
            {
                continue;
            }

            string entry = string.IsNullOrWhiteSpace(hop.User)
                ? hop.Host.Trim()
                : $"{hop.User.Trim()}@{hop.Host.Trim()}";

            int port = hop.Port > 0 ? hop.Port : 22;
            if (port != 22)
            {
                entry = $"{entry}:{port}";
            }

            chain.Add(entry);
        }

        return string.Join(",", chain);
    }

    private static void WriteFileAtomically(string path, string text)
    {
        string directory = Path.GetDirectoryName(path)
            ?? throw new InvalidOperationException("Generated config directory is missing.");
        string tempPath = Path.Combine(directory, $"{Path.GetFileName(path)}.{Guid.NewGuid():N}.tmp");

        File.WriteAllText(tempPath, text, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        try
        {
            if (File.Exists(path))
            {
                File.Move(tempPath, path, overwrite: true);
            }
            else
            {
                File.Move(tempPath, path);
            }
        }
        finally
        {
            if (File.Exists(tempPath))
            {
                File.Delete(tempPath);
            }
        }
    }

    private string GetKnownHostsFilePath()
    {
        if (!string.IsNullOrWhiteSpace(_options.KnownHostsFilePath))
        {
            return Path.GetFullPath(_options.KnownHostsFilePath);
        }

        return Path.Combine(_sshRootDirectory, "known_hosts");
    }

    private static string EscapeValue(string value)
    {
        bool requiresQuotes = value.Any(char.IsWhiteSpace) || value.Contains('#') || value.Contains('"');
        if (!requiresQuotes)
        {
            return value;
        }

        return $"\"{value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal)}\"";
    }

    /// <summary>The <c>Host</c> alias of <paramref name="profileId"/>'s block: what a plan names as ssh's destination.</summary>
    internal static string BuildAlias(Guid profileId)
    {
        return $"ntilde_{profileId:N}";
    }

    /// <remarks>
    /// Resolved through <see cref="PlatformAppPaths"/> for the same reason as
    /// <c>JsonSshProfileStore.GetDefaultStorePath</c>: reading LocalApplicationData directly ignored
    /// NTILDE_APPDATA_ROOT, so a redirected process still wrote generated OpenSSH config into the
    /// machine's real ssh directory (#406).
    /// </remarks>
    private static string GetDefaultSshRootDirectory() => PlatformAppPaths.SshDirectory;

    private static SshProfile CloneProfile(SshProfile profile)
    {
        return new SshProfile
        {
            Id = profile.Id,
            Name = profile.Name,
            Host = profile.Host,
            User = profile.User,
            Port = profile.Port,
            AuthMode = profile.AuthMode,
            IdentityFilePath = profile.IdentityFilePath,
            JumpHops = profile.JumpHops.Select(h => new SshJumpHop
            {
                Host = h.Host,
                User = h.User,
                Port = h.Port
            }).ToList(),
            Forwards = profile.Forwards.Select(f => new PortForward
            {
                Kind = f.Kind,
                BindAddress = f.BindAddress,
                SourcePort = f.SourcePort,
                DestinationHost = f.DestinationHost,
                DestinationPort = f.DestinationPort
            }).ToList(),
            MuxOptions = new SshMuxOptions
            {
                Enabled = profile.MuxOptions.Enabled,
                ControlMasterAuto = profile.MuxOptions.ControlMasterAuto,
                ControlPath = profile.MuxOptions.ControlPath,
                ControlPersistSeconds = profile.MuxOptions.ControlPersistSeconds,
                PersistRemoteSessions = profile.MuxOptions.PersistRemoteSessions,
                RemoteDaemonPath = profile.MuxOptions.RemoteDaemonPath,
                RemoteDaemonVersion = profile.MuxOptions.RemoteDaemonVersion,
                RemoteDaemonRid = profile.MuxOptions.RemoteDaemonRid
            },
            ServerAliveIntervalSeconds = profile.ServerAliveIntervalSeconds,
            ServerAliveCountMax = profile.ServerAliveCountMax,
            ExtraSshArgs = profile.ExtraSshArgs,
            WorkingDirectory = profile.WorkingDirectory
        };
    }
}
