using System.Security.Cryptography;
using System.Text;
using Ntilde.Platform.Ssh.Models;

namespace Ntilde.Platform.Ssh.OpenSsh;

public sealed class OpenSshConfigCompiler : IOpenSshConfigCompiler
{
    private readonly object _syncRoot = new();
    private readonly string _sshRootDirectory;
    private readonly string _generatedConfigPath;
    private readonly string _generatedHashPath;
    private readonly OpenSshCompilerOptions _options;

    public OpenSshConfigCompiler(string? sshRootDirectory = null, OpenSshCompilerOptions? options = null)
    {
        _sshRootDirectory = string.IsNullOrWhiteSpace(sshRootDirectory)
            ? GetDefaultSshRootDirectory()
            : Path.GetFullPath(sshRootDirectory);
        _generatedConfigPath = Path.Combine(_sshRootDirectory, "ssh_config.generated");
        _generatedHashPath = Path.Combine(_sshRootDirectory, "ssh_config.generated.hash");
        _options = options ?? new OpenSshCompilerOptions();
    }

    public OpenSshCompilationResult Compile(IReadOnlyList<SshProfile> profiles, Guid launchProfileId)
    {
        ArgumentNullException.ThrowIfNull(profiles);

        SshProfile launchProfile = profiles.FirstOrDefault(p => p.Id == launchProfileId)
            ?? throw new InvalidOperationException($"SSH profile '{launchProfileId}' was not found.");

        List<SshProfile> orderedProfiles = profiles
            .OrderBy(profile => profile.Id)
            .Select(CloneProfile)
            .ToList();

        string configText = BuildConfigText(orderedProfiles);
        string newHash = ComputeHash(configText);

        lock (_syncRoot)
        {
            Directory.CreateDirectory(_sshRootDirectory);
            Directory.CreateDirectory(Path.Combine(_sshRootDirectory, "mux"));
            if (_options.IsolateKnownHosts)
            {
                Directory.CreateDirectory(Path.GetDirectoryName(GetKnownHostsFilePath())!);
            }

            bool isCached = false;
            if (File.Exists(_generatedConfigPath) && File.Exists(_generatedHashPath))
            {
                try
                {
                    string existingHash = File.ReadAllText(_generatedHashPath).Trim();
                    isCached = string.Equals(existingHash, newHash, StringComparison.Ordinal);
                }
                catch
                {
                    isCached = false;
                }
            }

            if (!isCached)
            {
                WriteFileAtomically(_generatedConfigPath, configText);
                WriteFileAtomically(_generatedHashPath, newHash);
            }
        }

        return new OpenSshCompilationResult
        {
            ConfigFilePath = _generatedConfigPath,
            Alias = BuildAlias(launchProfile.Id)
        };
    }

    private string ComputeHash(string text)
    {
        byte[] bytes = Encoding.UTF8.GetBytes(text);
        byte[] hashBytes = SHA256.HashData(bytes);
        return Convert.ToHexString(hashBytes);
    }

    private string BuildConfigText(IReadOnlyList<SshProfile> profiles)
    {
        var sb = new StringBuilder(2048);
        sb.AppendLine("# Auto-generated by Ntilde. Changes will be overwritten.");
        sb.AppendLine();

        foreach (SshProfile profile in profiles)
        {
            AppendHostBlock(sb, profile);
        }

        return sb.ToString();
    }

    private void AppendHostBlock(StringBuilder sb, SshProfile profile)
    {
        string alias = BuildAlias(profile.Id);

        sb.Append("Host ").Append(alias).AppendLine();
        sb.Append("  HostName ").Append(EscapeValue(profile.Host.Trim())).AppendLine();

        if (!string.IsNullOrWhiteSpace(profile.User))
        {
            sb.Append("  User ").Append(EscapeValue(profile.User.Trim())).AppendLine();
        }

        int port = profile.Port > 0 ? profile.Port : 22;
        int serverAliveInterval = profile.ServerAliveIntervalSeconds > 0 ? profile.ServerAliveIntervalSeconds : 30;
        int serverAliveCountMax = profile.ServerAliveCountMax > 0 ? profile.ServerAliveCountMax : 3;
        sb.Append("  Port ").Append(port.ToString()).AppendLine();
        sb.Append("  ServerAliveInterval ").Append(serverAliveInterval.ToString()).AppendLine();
        sb.Append("  ServerAliveCountMax ").Append(serverAliveCountMax.ToString()).AppendLine();

        if (profile.AuthMode == SshAuthMode.IdentityFile && !string.IsNullOrWhiteSpace(profile.IdentityFilePath))
        {
            sb.Append("  IdentityFile ").Append(EscapeValue(profile.IdentityFilePath.Trim())).AppendLine();
            sb.AppendLine("  IdentitiesOnly yes");
        }

        string jumpChain = BuildProxyJumpValue(profile.JumpHops);
        if (!string.IsNullOrEmpty(jumpChain))
        {
            sb.Append("  ProxyJump ").Append(jumpChain).AppendLine();
        }

        foreach (PortForward forward in profile.Forwards)
        {
            AppendForward(sb, forward);
        }

        if (_options.IsolateKnownHosts)
        {
            sb.Append("  UserKnownHostsFile ").Append(EscapeValue(GetKnownHostsFilePath())).AppendLine();
        }

        AppendMuxOptions(sb, profile);
        sb.AppendLine();
    }

    private void AppendMuxOptions(StringBuilder sb, SshProfile profile)
    {
        if (!profile.MuxOptions.Enabled)
        {
            return;
        }

        if (profile.MuxOptions.ControlMasterAuto)
        {
            sb.AppendLine("  ControlMaster auto");
        }

        if (profile.MuxOptions.ControlPersistSeconds > 0)
        {
            sb.Append("  ControlPersist ")
                .Append(profile.MuxOptions.ControlPersistSeconds.ToString())
                .AppendLine();
        }

        string controlPath = GetResolvedControlPath(profile);
        sb.Append("  ControlPath ").Append(EscapeValue(controlPath)).AppendLine();
    }

    private string GetResolvedControlPath(SshProfile profile)
    {
        string raw = profile.MuxOptions.ControlPath?.Trim() ?? string.Empty;
        if (string.IsNullOrEmpty(raw))
        {
            raw = Path.Combine(_sshRootDirectory, "mux", "cm_%id%");
        }

        string profileIdToken = profile.Id.ToString("N");
        return raw.Replace("%id%", profileIdToken, StringComparison.OrdinalIgnoreCase);
    }

    private static void AppendForward(StringBuilder sb, PortForward forward)
    {
        if (forward.SourcePort <= 0)
        {
            return;
        }

        string bind = string.IsNullOrWhiteSpace(forward.BindAddress)
            ? forward.SourcePort.ToString()
            : $"{forward.BindAddress.Trim()}:{forward.SourcePort}";

        switch (forward.Kind)
        {
            case PortForwardKind.Local:
                if (string.IsNullOrWhiteSpace(forward.DestinationHost) || forward.DestinationPort <= 0)
                {
                    return;
                }

                sb.Append("  LocalForward ")
                    .Append(bind)
                    .Append(' ')
                    .Append(forward.DestinationHost.Trim())
                    .Append(':')
                    .Append(forward.DestinationPort.ToString())
                    .AppendLine();
                break;

            case PortForwardKind.Remote:
                if (string.IsNullOrWhiteSpace(forward.DestinationHost) || forward.DestinationPort <= 0)
                {
                    return;
                }

                sb.Append("  RemoteForward ")
                    .Append(bind)
                    .Append(' ')
                    .Append(forward.DestinationHost.Trim())
                    .Append(':')
                    .Append(forward.DestinationPort.ToString())
                    .AppendLine();
                break;

            case PortForwardKind.Dynamic:
                sb.Append("  DynamicForward ").Append(bind).AppendLine();
                break;
        }
    }

    private static string BuildProxyJumpValue(IEnumerable<SshJumpHop> jumpHops)
    {
        List<string> chain = new();

        foreach (SshJumpHop hop in jumpHops)
        {
            if (string.IsNullOrWhiteSpace(hop.Host))
            {
                continue;
            }

            string entry = string.IsNullOrWhiteSpace(hop.User)
                ? hop.Host.Trim()
                : $"{hop.User.Trim()}@{hop.Host.Trim()}";

            int port = hop.Port > 0 ? hop.Port : 22;
            if (port != 22)
            {
                entry = $"{entry}:{port}";
            }

            chain.Add(entry);
        }

        return string.Join(",", chain);
    }

    private static void WriteFileAtomically(string path, string text)
    {
        string directory = Path.GetDirectoryName(path)
            ?? throw new InvalidOperationException("Generated config directory is missing.");
        string tempPath = Path.Combine(directory, $"{Path.GetFileName(path)}.{Guid.NewGuid():N}.tmp");

        File.WriteAllText(tempPath, text, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        try
        {
            if (File.Exists(path))
            {
                File.Move(tempPath, path, overwrite: true);
            }
            else
            {
                File.Move(tempPath, path);
            }
        }
        finally
        {
            if (File.Exists(tempPath))
            {
                File.Delete(tempPath);
            }
        }
    }

    private string GetKnownHostsFilePath()
    {
        if (!string.IsNullOrWhiteSpace(_options.KnownHostsFilePath))
        {
            return Path.GetFullPath(_options.KnownHostsFilePath);
        }

        return Path.Combine(_sshRootDirectory, "known_hosts");
    }

    private static string EscapeValue(string value)
    {
        bool requiresQuotes = value.Any(char.IsWhiteSpace) || value.Contains('#') || value.Contains('"');
        if (!requiresQuotes)
        {
            return value;
        }

        return $"\"{value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal)}\"";
    }

    private static string BuildAlias(Guid profileId)
    {
        return $"ntilde_{profileId:N}";
    }

    /// <remarks>
    /// Resolved through <see cref="PlatformAppPaths"/> for the same reason as
    /// <c>JsonSshProfileStore.GetDefaultStorePath</c>: reading LocalApplicationData directly ignored
    /// NTILDE_APPDATA_ROOT, so a redirected process still wrote generated OpenSSH config into the
    /// machine's real ssh directory (#406).
    /// </remarks>
    private static string GetDefaultSshRootDirectory() => PlatformAppPaths.SshDirectory;

    private static SshProfile CloneProfile(SshProfile profile)
    {
        return new SshProfile
        {
            Id = profile.Id,
            Name = profile.Name,
            Host = profile.Host,
            User = profile.User,
            Port = profile.Port,
            AuthMode = profile.AuthMode,
            IdentityFilePath = profile.IdentityFilePath,
            JumpHops = profile.JumpHops.Select(h => new SshJumpHop
            {
                Host = h.Host,
                User = h.User,
                Port = h.Port
            }).ToList(),
            Forwards = profile.Forwards.Select(f => new PortForward
            {
                Kind = f.Kind,
                BindAddress = f.BindAddress,
                SourcePort = f.SourcePort,
                DestinationHost = f.DestinationHost,
                DestinationPort = f.DestinationPort
            }).ToList(),
            MuxOptions = new SshMuxOptions
            {
                Enabled = profile.MuxOptions.Enabled,
                ControlMasterAuto = profile.MuxOptions.ControlMasterAuto,
                ControlPath = profile.MuxOptions.ControlPath,
                ControlPersistSeconds = profile.MuxOptions.ControlPersistSeconds
            },
            ServerAliveIntervalSeconds = profile.ServerAliveIntervalSeconds,
            ServerAliveCountMax = profile.ServerAliveCountMax,
            ExtraSshArgs = profile.ExtraSshArgs,
            WorkingDirectory = profile.WorkingDirectory
        };
    }
}
