using System.Globalization;
using System.Linq;
using System.Text;

namespace Ntilde.VT;

// Partial: the East_Asian_Width and text-default emoji tables live in UnicodeWidth.Tables.g.cs,
// generated by scripts/gen-unicode-width.py.
public static partial class UnicodeWidth
{
    // Takes a span rather than a string so the VT write path can measure a grapheme without
    // materializing one (#165). string converts implicitly, so existing callers are unaffected.
    public static int GetGraphemeWidth(ReadOnlySpan<char> textElement)
    {
        if (textElement.IsEmpty)
        {
            return 0;
        }

        if (textElement.Length == 1)
        {
            return Rune.TryCreate(textElement[0], out var rune) ? GetRuneWidth(rune) : 1;
        }

        int totalBaseWidth = 0;
        int regionalIndicatorCount = 0;
        int nonRegionalBaseCount = 0;
        bool hasEmojiModifier = false;
        bool hasEmojiPresentation = false;
        bool hasTextPresentation = false;
        bool hasZwj = false;
        bool hasTextDefaultEmojiBase = false;
        bool hasWideEmojiBase = false;

        foreach (var rune in textElement.EnumerateRunes())
        {
            if (IsZeroWidthJoiner(rune))
            {
                hasZwj = true;
                continue;
            }

            if (IsVariationSelector15(rune))
            {
                hasTextPresentation = true;
                continue;
            }

            if (IsVariationSelector16(rune))
            {
                hasEmojiPresentation = true;
                continue;
            }

            if (IsEmojiModifier(rune))
            {
                hasEmojiModifier = true;
                continue;
            }

            if (IsZeroWidthGraphemeComponent(rune))
            {
                continue;
            }

            if (IsTextDefaultEmoji(rune.Value))
            {
                hasTextDefaultEmojiBase = true;
            }

            if (IsRegionalIndicator(rune))
            {
                regionalIndicatorCount++;
            }
            else
            {
                nonRegionalBaseCount++;
            }

            int width = GetRuneWidth(rune);
            totalBaseWidth += width;

            if (width == 2 && (IsRegionalIndicator(rune) || IsEmojiRange(rune)))
            {
                hasWideEmojiBase = true;
            }
        }

        if (regionalIndicatorCount > 0 && nonRegionalBaseCount == 0)
        {
            int pairs = regionalIndicatorCount / 2;
            int remainder = regionalIndicatorCount % 2;
            return (pairs * 2) + (remainder * 2);
        }

        if (hasZwj)
        {
            if (hasWideEmojiBase || hasTextDefaultEmojiBase)
            {
                return 2;
            }

            return totalBaseWidth == 0 ? 0 : Math.Max(1, totalBaseWidth);
        }

        if (hasEmojiModifier)
        {
            if (totalBaseWidth == 0)
            {
                return 0;
            }

            return Math.Max(2, totalBaseWidth);
        }

        // Presentation decides width only for text-default emoji: VS16 turns them into a two-cell
        // emoji. On any other base VS16 is an unsupported sequence that applications measure as
        // the base plus a zero-width selector, so widening there would move the cursor.
        if (hasTextDefaultEmojiBase)
        {
            if (hasEmojiPresentation)
            {
                return Math.Max(2, totalBaseWidth);
            }

            if (hasTextPresentation)
            {
                return totalBaseWidth == 0 ? 1 : totalBaseWidth;
            }
        }

        return totalBaseWidth;
    }

    public static int GetRuneWidth(Rune rune)
    {
        if (IsZeroWidthGraphemeComponent(rune))
        {
            return 0;
        }

        int cp = rune.Value;

        if (cp < 32 || (cp >= 0x7F && cp <= 0x9F))
        {
            return 0;
        }

        // Double width is exactly East_Asian_Width W or F, because that is the set wcwidth uses
        // and so what every application measures with; any other answer puts the cursor where
        // the application does not expect it. This used to be nine hand-written ranges, which
        // missed the BMP emoji that are W (U+2705, U+26A1, U+2B50, ...) and made everything in
        // U+1F000..U+1FBFF wide, including narrow sextants, arrows and text-default pictographs.
        return IsEastAsianWide(cp) ? 2 : 1;
    }

    // The bounds check means everything below U+1100 (ASCII, Latin, Greek, Cyrillic, ...), which
    // is nearly all terminal output, returns without searching.
    internal static bool IsEastAsianWide(int codePoint)
        => InRanges(EastAsianWideRanges, EastAsianWideMin, EastAsianWideMax, codePoint);

    // Emoji=Yes, Emoji_Presentation=No, not already wide: the bases VS16 widens (U+2764, U+00A9,
    // U+25B6, the keycap digits, U+1F321, ...). Generated from Unicode data rather than taken as
    // block spans, which widened non-emoji symbols such as U+2605 or U+1F700 under VS16 and missed
    // text-default emoji outside the spans.
    internal static bool IsTextDefaultEmoji(int codePoint)
        => InRanges(TextDefaultEmojiRanges, TextDefaultEmojiMin, TextDefaultEmojiMax, codePoint);

    // Binary search over generated (start, end) pairs, after a bounds check against the table's
    // lowest and highest code point.
    private static bool InRanges(ReadOnlySpan<int> ranges, int min, int max, int codePoint)
    {
        if (codePoint < min || codePoint > max)
        {
            return false;
        }

        int lo = 0;
        int hi = (ranges.Length / 2) - 1;
        while (lo <= hi)
        {
            int mid = lo + ((hi - lo) / 2);
            if (codePoint < ranges[mid * 2])
            {
                hi = mid - 1;
            }
            else if (codePoint > ranges[(mid * 2) + 1])
            {
                lo = mid + 1;
            }
            else
            {
                return true;
            }
        }

        return false;
    }

    public static bool IsZeroWidthGraphemeComponent(Rune rune)
    {
        UnicodeCategory category = Rune.GetUnicodeCategory(rune);
        if (category == UnicodeCategory.NonSpacingMark ||
            category == UnicodeCategory.SpacingCombiningMark ||
            category == UnicodeCategory.EnclosingMark)
        {
            return true;
        }

        int value = rune.Value;
        if (value >= 0x200B && value <= 0x200F) return true;
        if (value >= 0xFE00 && value <= 0xFE0F) return true;
        if (value >= 0xE0100 && value <= 0xE01EF) return true;
        if (value >= 0x1F3FB && value <= 0x1F3FF) return true;
        if (value >= 0xE0020 && value <= 0xE007F) return true;

        return false;
    }

    // Spans, for the same reason as GetGraphemeWidth (#165).
    public static bool ShouldAttachToPrevious(ReadOnlySpan<char> previousGrapheme, ReadOnlySpan<char> incomingGrapheme, bool previousEndedWithZwj)
    {
        if (previousGrapheme.IsEmpty || incomingGrapheme.IsEmpty)
        {
            return false;
        }

        if (previousEndedWithZwj)
        {
            return true;
        }

        if (TryGetFirstRune(incomingGrapheme, out var incomingRune) && IsZeroWidthGraphemeComponent(incomingRune))
        {
            return true;
        }

        if (IsSingleRegionalIndicator(incomingGrapheme) && IsRegionalIndicatorCluster(previousGrapheme))
        {
            return CountRegionalIndicators(previousGrapheme) % 2 == 1;
        }

        return false;
    }

    public static bool IsRegionalIndicatorCluster(ReadOnlySpan<char> text)
    {
        if (CountRegionalIndicators(text) == 0) return false;

        // Was `text.EnumerateRunes().All(IsRegionalIndicator)`; the LINQ call boxed the struct
        // enumerator on a path the write loop reaches per grapheme (#165).
        foreach (var rune in text.EnumerateRunes())
        {
            if (!IsRegionalIndicator(rune)) return false;
        }
        return true;
    }

    public static bool IsSingleRegionalIndicator(ReadOnlySpan<char> text)
    {
        if (text.IsEmpty)
        {
            return false;
        }

        int count = 0;
        foreach (var rune in text.EnumerateRunes())
        {
            if (!IsRegionalIndicator(rune))
            {
                return false;
            }

            count++;
            if (count > 1)
            {
                return false;
            }
        }

        return count == 1;
    }

    public static int CountRegionalIndicators(ReadOnlySpan<char> text)
    {
        if (text.IsEmpty)
        {
            return 0;
        }

        int count = 0;
        foreach (var rune in text.EnumerateRunes())
        {
            if (IsRegionalIndicator(rune))
            {
                count++;
            }
        }

        return count;
    }

    public static bool IsZeroWidthJoiner(Rune rune) => rune.Value == 0x200D;

    public static bool IsRegionalIndicator(Rune rune)
        => rune.Value >= 0x1F1E6 && rune.Value <= 0x1F1FF;

    public static bool IsVariationSelector15(Rune rune) => rune.Value == 0xFE0E;

    public static bool IsVariationSelector16(Rune rune) => rune.Value == 0xFE0F;

    public static bool IsEmojiModifier(Rune rune)
        => rune.Value >= 0x1F3FB && rune.Value <= 0x1F3FF;

    // The SMP symbol and pictograph blocks, used only with GetRuneWidth == 2 to spot a wide emoji
    // in a ZWJ sequence. A block span, not a width claim.
    private static bool IsEmojiRange(Rune rune)
        => rune.Value >= 0x1F000 && rune.Value <= 0x1FBFF;

    private static bool TryGetFirstRune(ReadOnlySpan<char> text, out Rune rune)
    {
        if (text.IsEmpty)
        {
            rune = default;
            return false;
        }

        foreach (var candidate in text.EnumerateRunes())
        {
            rune = candidate;
            return true;
        }

        rune = default;
        return false;
    }
}
