<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="SharpFuzz" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Ntilde.VT\Ntilde.VT.csproj" />
  </ItemGroup>

</Project>
