#!/usr/bin/env python3
"""Generate the double-width code point table behind Ntilde.VT.UnicodeWidth.GetRuneWidth.

A terminal has to agree with applications about how many cells a character takes, or the cursor
lands a column away from where the application believes it is and TUIs misdraw from there on.
Applications measure with wcwidth (glibc, Node, Rust's unicode-width, ...), and wcwidth's
double-width set is Unicode's East_Asian_Width property with value W (wide) or F (fullwidth),
UAX #11. This script emits exactly that set as sorted, merged, inclusive code point ranges.

The table used to be nine hand-written ranges. They missed BMP emoji that are EAW=W (U+2705,
U+274C, U+26A1, U+2B50, ...), and a blanket U+1F000..U+1FBFF range made narrow symbols such as
the legacy-computing sextants and the text-presentation pictographs wide. Deriving the table from
the Unicode Character Database removes the guesswork, and regenerating it is how the terminal
follows new Unicode versions.

Source: Python's own `unicodedata` module, so no download is involved and the Unicode version is
whatever the running interpreter ships (`unicodedata.unidata_version`, written into the output
header). It already applies UAX #11's defaults for unassigned code points, so the reserved parts
of the CJK blocks and all of Planes 2 and 3 come out wide and future ideographs land correctly.

Only the rune table lives here. Zero-width marks, controls and the grapheme-level rules (emoji
selectors, ZWJ sequences, flags, skin-tone modifiers) are hand-written in UnicodeWidth.cs and run
before or on top of this lookup.

Usage: gen-unicode-width.py [--check]

  (no args)  Rewrite src/Ntilde.VT/UnicodeWidth.EastAsianWide.g.cs.
  --check    Write nothing; exit 1 if the committed file differs from what this interpreter's
             Unicode data would generate.
"""

import sys
import unicodedata
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = REPO_ROOT / "src" / "Ntilde.VT" / "UnicodeWidth.EastAsianWide.g.cs"
SCRIPT = "scripts/gen-unicode-width.py"
WIDE_CLASSES = ("W", "F")


def wide_ranges():
    """Inclusive (start, end) ranges of every code point whose East_Asian_Width is W or F."""
    ranges = []
    start = None
    for cp in range(0x110000 + 1):
        wide = cp <= 0x10FFFF and unicodedata.east_asian_width(chr(cp)) in WIDE_CLASSES
        if wide and start is None:
            start = cp
        elif not wide and start is not None:
            ranges.append((start, cp - 1))
            start = None
    return ranges


def label(cp):
    ch = chr(cp)
    name = unicodedata.name(ch, "")
    if name:
        return name
    category = unicodedata.category(ch)
    return "<unassigned>" if category == "Cn" else f"<unnamed {category}>"


def render(ranges, version):
    lines = [
        "// <auto-generated>",
        f"//     Generated by {SCRIPT} from the Unicode {version} East_Asian_Width",
        "//     property (the unicodedata module of the Python that ran it). Do not edit by hand.",
        "//",
        "//     To regenerate, run from the repository root with a Python whose",
        "//     unicodedata.unidata_version is the Unicode version you want:",
        f"//         python {SCRIPT}",
        f"//     and `python {SCRIPT} --check` verifies the committed file is current.",
        "// </auto-generated>",
        "",
        "namespace Ntilde.VT;",
        "",
        "public static partial class UnicodeWidth",
        "{",
        "    /// <summary>Unicode version the East_Asian_Width table below was generated from.</summary>",
        f"    internal const string EastAsianWidthUnicodeVersion = \"{version}\";",
        "",
        "    /// <summary>Lowest code point in <see cref=\"EastAsianWideRanges\"/>; everything below is narrow.</summary>",
        f"    internal const int EastAsianWideMin = 0x{ranges[0][0]:04X};",
        "",
        "    /// <summary>Highest code point in <see cref=\"EastAsianWideRanges\"/>; everything above is narrow.</summary>",
        f"    internal const int EastAsianWideMax = 0x{ranges[-1][1]:04X};",
        "",
        "    /// <summary>",
        "    /// Code points whose East_Asian_Width is W or F, as inclusive (start, end) pairs sorted",
        "    /// ascending, non-overlapping and merged, so a binary search over the pairs is exact.",
        "    /// </summary>",
        "    internal static ReadOnlySpan<int> EastAsianWideRanges => _eastAsianWideRanges;",
        "",
        "    // A static array, not `ReadOnlySpan<int> X => new int[] { ... }`. That form is free only where",
        "    // the JIT expands RuntimeHelpers.CreateSpan as an intrinsic; unoptimized (Debug) code calls the",
        "    // managed fallback, which allocates on every access - 72 bytes a lookup, measured.",
        "    private static readonly int[] _eastAsianWideRanges =",
        "    {",
    ]
    for start, end in ranges:
        if start == end:
            comment = label(start)
        else:
            comment = f"{label(start)}..{label(end)}"
        lines.append(f"        0x{start:04X}, 0x{end:04X}, // {comment}")
    lines += [
        "    };",
        "}",
        "",
    ]
    return "\r\n".join(lines)


def main(argv):
    check = argv[1:] == ["--check"]
    if argv[1:] and not check:
        print(__doc__, file=sys.stderr)
        return 2

    ranges = wide_ranges()
    version = unicodedata.unidata_version
    text = render(ranges, version)

    if check:
        current = OUTPUT.read_bytes().decode("utf-8") if OUTPUT.exists() else ""
        # git may check the file out with either line ending, depending on the platform's config.
        if current.replace("\r\n", "\n") != text.replace("\r\n", "\n"):
            print(f"{OUTPUT.relative_to(REPO_ROOT).as_posix()} is out of date for Unicode {version}; "
                  f"run: python {SCRIPT}", file=sys.stderr)
            return 1
        print(f"{OUTPUT.relative_to(REPO_ROOT).as_posix()} is current for Unicode {version} ({len(ranges)} ranges).")
        return 0

    # CRLF and no BOM, matching .editorconfig and the *.cs rule in .gitattributes.
    OUTPUT.write_bytes(text.encode("utf-8"))
    print(f"Wrote {OUTPUT.relative_to(REPO_ROOT).as_posix()}: {len(ranges)} ranges, Unicode {version}.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
